"""add Department

Revision ID: 5a65a1b21adf
Revises: 652675759f8f
Create Date: 2025-09-13 17:48:16.414007

"""
from alembic import op
import sqlalchemy as sa  # type: ignore


# revision identifiers, used by Alembic.
revision = '5a65a1b21adf'
down_revision = '652675759f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
